### ISSUE TITLE
由于git文件大小限制, 无法上传数据库文件

### ISSUE THREAD

**Issue by XiaoSenLuo** [XiaoSenLuo/CadenceLibrary#1]
由于git文件大小限制, 无法上传数据库文件, github有LFS免费空间限制, 所以数据文件暂时无法上传, 导出SQL脚本依旧很大, 解决办法待定

**Comment by XiaoSenLuo** [comment]
数据文件导出到CSV文件

**Comment by Vinci-H** [comment]
感谢作者，pcb库文件很棒，自己打算建一波常用器件数据库access文件；
